site_name: My AI Blog
theme:
  name: material
  features:
    - navigation.expand
    - navigation.top
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
nav:
  - Home: index.md
  - Blogs:
      - First Blog: blogs/first-blog.md
      - Second Blog: blogs/second-blog.md
